### ISSUE TITLE
Tree widget is not expanding beyond 2 levels for input parameters.

### ISSUE THREAD

**Issue by dineshshetye** [hpcc-systems/DeprecatedPendingDeletionDashboard#69]
Tree widget is not expanding beyond 2 levels for input parameters.

**Query:** attributemonitor_generic_ir14c
**Level1:** Root
**Level2:** distributionname
**Level3:** modelid
**Level4:** scorerange

![image](https://cloud.githubusercontent.com/assets/1731313/8678975/e3255bec-2a25-11e5-949e-962aedc4bf7e.png)

**Comment by Ilakkiya-Sivaraj** [comment]
![image](https://cloud.githubusercontent.com/assets/6291537/8691378/45e0705a-2adf-11e5-9a23-fcdca63e2833.png)

Tree chart is working fine.
By default only first level is expanded. Other levels will be expanded on-demand.

Please avoid providing input parametrs for the columns that are used in tree. Because tree will supply parent node values as input parameters upon retriving the next level. ie, in the above screen shot if model Id is not provided as input there would be more than one node at third level.

However, when there are two tree charts in a single dashboard, one of them is not responding to clicks. I'm working on this.

Also, roxie queries in our cluster is working intermittently
